namespace Skyline.DataMiner.Automation
{
	/// <summary>
	/// Specifies the runtime flags.
	/// </summary>
	public enum RunTimeFlags
	{
		/// <summary>
		/// None.
		/// </summary>
		None = 0,
		/// <summary>
		/// By default, C# code used in an automation script throws an exception when it encounters an undefined or an empty parameter. However, if you add the following line in an automation script statement of type “CSharp Code”, then null will be returned instead:
		/// </summary>
		AllowUndef = 16,
		/// <summary>
		/// Activate this option to prevent information events from being generated by the SET statements in the script.
		/// </summary>
		NoInformationEvents = 32,
		/// <summary>
		/// Activate this option to prevent caching of table key mappings. By default, within a C# code block, lists of primary key/display key mappings are cached for perfor­mance reasons. To prevent caching of table key mappings, add the following statement to your automation script.
		/// </summary>
		NoKeyCaching = 64,
		/// <summary>
		/// Use this flag to disable checking the parameter or property after changing it from an automation script. Feature introduced in DataMiner 10.0.8 (RN 25847).
		/// </summary>
		NoCheckingSets = 128
	}
}