graph TD
    A[AutomationConfigOptions]
    B[AutomationDateTimeUpDownOptions]
    C[AutomationTimeUpDownOptions]
    D[AutomationDateTimePickerOptions]
    E[AutomationTimePickerOptions]
    F[AutomationCalendarOptions]

    A --> B
    A --> C
    B --> D
    B --> E
    A --> F